name: diet_helper
description: Diet Helper
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # API
  retrofit: ^4.2.0
  dio: ^5.6.0
  json_annotation: ^4.9.0
  http_parser: ^4.0.2
  universal_io: ^2.2.2

  # DI
  get_it: ^8.0.3
  injectable: ^2.4.4

  #State Management
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.3

  # Utils
  flutter_i18n: ^0.36.2
  collection: ^1.18.0
  go_router: ^14.2.6
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  mutex: ^3.1.0
  connectivity_plus: ^6.0.5
  image: ^4.2.0
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  device_info_plus: ^11.3.3
  mask_text_input_formatter: ^2.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  flutter_widget_from_html: ^0.16.0
  toggle_switch: ^2.3.0

  # UI
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flash: ^3.1.1
  avatar_glow: ^3.0.1
  loader_overlay: ^5.0.0
  lazy_load_indexed_stack: ^1.1.0
  flutter_animate: ^4.5.0
  transparent_pointer: ^1.0.1
  smooth_page_indicator: ^1.2.0+3
  blur: ^4.0.0
  searchfield: ^1.0.9
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.26
  flutter_native_splash: ^2.4.1
  percent_indicator: ^4.2.3
  file_picker: ^9.1.0
  carousel_slider: 5.0.0
  webview_flutter: ^4.9.0
  file_saver: ^0.2.12
  flutter_html: ^3.0.0-beta.2

# Message
  customer_io: ^2.1.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  # Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # Audio/Video
  audio_waveforms: ^1.0.5
  video_player: ^2.9.1
  photo_view: ^0.15.0
  camera: ^0.11.0+2
  subtitle_wrapper_package: ^2.2.1

  #   .ice
  wakelock_plus: ^1.2.8

  # DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  #Sentry
  sentry_flutter: ^8.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9
  version: ^3.0.2
  flutter_gen: ^5.6.0
  flutter_gen_runner: ^5.6.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/colors/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
